analise = input('Digite algo, qualquer coisa e vamos analisar: ')
print('O tipo primirivo desse valor é: {}'.format(type(analise)))
print('Só tem espaços? {}'.format(analise.isspace()))
print('É um número? {}'.format(analise.isnumeric()))
print('É alfabetico? {}'.format(analise.isalpha()))
print('É alfanumérico? {}'.format(analise.isalnum()))
print('Está em minúculas? {}'.format(analise.islower()))
print('Está em maiúsculas? {}'.format(analise.isupper()))
print('Está capitalizada? {}'.format(analise.istitle()))
